"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, LockKeyhole } from "lucide-react";
import { api, ApiError } from "../../lib/api";

export default function Connect() {
 const router=useRouter(); const [id,setId]=useState(""); const [season,setSeason]=useState(2026); const [team,setTeam]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<ApiError>();
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(undefined);try{const result=await api<{warnings?:string[]}>("/api/connect",{method:"POST",body:JSON.stringify({league_id:id.trim(),season,team_id:team.trim()||null})});if(result.warnings?.length)sessionStorage.setItem("connection_warnings",JSON.stringify(result.warnings));router.push("/dashboard")}catch(x){if(x instanceof ApiError&&x.code==="LEAGUE_NOT_FOUND"){setError(new ApiError({code:x.code,message:"That ESPN league ID doesn’t exist for the selected season.",hint:"Check the league ID and season for a typo. If the league is private, also verify the backend’s ESPN credentials.",retryable:false},x.status))}else{setError(x instanceof ApiError?x:new ApiError({code:"CONNECTION_FAILED",message:"The league could not be connected.",hint:"Check your information and try again.",retryable:true},0))}}finally{setBusy(false)}}
 return <main className="connect-page"><Link className="back" href="/"><ArrowLeft size={17}/> Home</Link><section className="connect-card"><div className="step">LIVE ESPN CONNECTION</div><h1>Connect your ESPN league</h1><p>Enter a numeric ESPN league ID. Fourth Down does not substitute demo data when a live league is unavailable.</p><form onSubmit={submit}><label>League ID<input value={id} onChange={e=>setId(e.target.value)} inputMode="numeric" pattern="[0-9]{1,30}" aria-describedby="league-help" required/><small id="league-help">The number in your ESPN league URL—not your team name.</small></label><div className="form-row"><label>Season<input type="number" min="2020" max="2030" value={season} onChange={e=>setSeason(+e.target.value)} /></label><label>Your team ID <span>optional</span><input value={team} onChange={e=>setTeam(e.target.value)} inputMode="numeric" pattern="[0-9]{0,10}" placeholder="Select first team"/></label></div>{error&&<div className="friendly-error" role="alert"><b>{error.message}</b><p>{error.hint}</p><small>Error code: {error.code}</small></div>}<button className="button" disabled={busy}>{busy?"Checking ESPN…":"Connect league"}<ArrowRight size={18}/></button></form><aside><LockKeyhole size={19}/><div><b>Private league?</b><p>Use the Streamlit deployment for password-masked, session-only ESPN cookie fields. Never commit ESPN credentials.</p></div></aside></section></main>
}
