"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, BarChart3, CheckCircle2, Download, FlaskConical, Search, ShieldCheck, Sparkles, TrendingUp, Trophy, Users } from "lucide-react";
import { API, api } from "../lib/api";

type Player={id:string;name:string;position:string;team:string;mean:number;stdev:number;injury_status:string};
type Trade={send:Player[];receive:Player[];required_drop?:Player;before:{floor:number;median:number;ceiling:number};after:{floor:number;median:number;ceiling:number};weekly_delta:number;playoff_delta:number;championship_delta:number;acceptance_likelihood:number;verdict:string;reasons:string[];risks:string[]};
type Strength={team_id:string;team_name:string;rank:number;expected_score:number;playoff_probability:number;championship_probability:number;projected_wins:number;wins_low:number;wins_high:number};
const pct=(n:number)=>`${Math.round(n*100)}%`;
function Head({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <header className="page-head"><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></header>}
function Loading(){return <div className="loading"><Sparkles/><b>Running simulations…</b></div>}

export function DraftPage(){const [mode,setMode]=useState("balanced");const [data,setData]=useState<any>();useEffect(()=>{setData(undefined);api(`/api/draft?mode=${mode}`).then(setData)},[mode]);return <main className="page"><Head eyebrow="LIVE DRAFT BOARD" title="Draft for the roster you have." copy="Value over replacement, roster need, scarcity, and uncertainty—not a static rank list."/><div className="control-bar"><div>{["safe","balanced","ceiling"].map(x=><button className={mode===x?"active":""} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><span>{data?.method}</span></div>{!data?<Loading/>:<div className="draft-board">{data.recommendations.map((r:any)=><article key={r.player.id}><b className="draft-rank">{r.rank}</b><div><span className="position-chip">{r.player.position}</span><h3>{r.player.name}</h3><p>{r.player.team} · {r.roster_fit}</p></div><Metric label="VOR" value={`${r.vor>0?"+":""}${r.vor}`}/><Metric label="SURVIVES" value={pct(r.survival_probability)}/><Metric label="RISK" value={r.risk}/><p className="board-explain">{r.explanation}</p></article>)}</div>}</main>}

export function TradesPage(){const [data,setData]=useState<any>();const [send,setSend]=useState("");const [receive,setReceive]=useState("");const [result,setResult]=useState<Trade>();const [busy,setBusy]=useState(false);useEffect(()=>{api("/api/trades").then((x:any)=>{setData(x);setSend(x.your_players[0]?.id||"");setReceive(x.opponents[0]?.players[0]?.id||"")})},[]);async function evaluate(e:FormEvent){e.preventDefault();setBusy(true);setResult(await api("/api/trades/evaluate",{method:"POST",body:JSON.stringify({send_ids:[send],receive_ids:[receive],opponent_team_id:data.opponents[0].id})}));setBusy(false)}if(!data)return <main className="page"><Loading/></main>;return <main className="page"><Head eyebrow="TRADE LAB" title="Evaluate the whole roster." copy="The player you receive matters. So does the starter they displace and any required drop."/><form className="trade-builder" onSubmit={evaluate}><label>YOU SEND<select value={send} onChange={e=>setSend(e.target.value)}>{data.your_players.map((p:Player)=><option value={p.id} key={p.id}>{p.name} · {p.position}</option>)}</select></label><ArrowRight/><label>YOU RECEIVE<select value={receive} onChange={e=>setReceive(e.target.value)}>{data.opponents[0].players.map((p:Player)=><option value={p.id} key={p.id}>{p.name} · {p.position}</option>)}</select></label><button className="button">{busy?"Simulating…":"Evaluate trade"}</button></form>{result&&<TradeCard trade={result}/>}<h2 className="section-title"><Sparkles/> Generated offers</h2><div className="idea-grid">{data.ideas.map((t:Trade,i:number)=><TradeCard trade={t} key={i} compact/>)}</div></main>}
function TradeCard({trade,compact}:{trade:Trade;compact?:boolean}){return <article className={compact?"trade-result compact":"trade-result"}><div className="card-top"><span>{trade.verdict}</span><span>{pct(trade.acceptance_likelihood)} ACCEPTANCE</span></div><h3>{trade.send.map(x=>x.name).join(" + ")} <ArrowRight/> {trade.receive.map(x=>x.name).join(" + ")}</h3><div className="compare"><Metric label="WEEKLY" value={`${trade.weekly_delta>=0?"+":""}${trade.weekly_delta}`}/><Metric label="PLAYOFF" value={`${trade.playoff_delta>=0?"+":""}${pct(trade.playoff_delta)}`}/><Metric label="TITLE" value={`${trade.championship_delta>=0?"+":""}${pct(trade.championship_delta)}`}/></div>{!compact&&<><p>{trade.reasons.join(" ")}</p><small>{trade.risks[0]}</small></>}</article>}

export function PlayersPage(){const [q,setQ]=useState("");const [players,setPlayers]=useState<Player[]>([]);useEffect(()=>{api<{players:Player[]}>(`/api/players?q=${encodeURIComponent(q)}`).then(x=>setPlayers(x.players))},[q]);return <main className="page"><Head eyebrow="PLAYER RESEARCH" title="Search every decision variable." copy="Projection range, role, availability, and market-data honesty in one view."/><label className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player or NFL team"/></label><div className="player-directory">{players.map(p=><Link href={`/players/${p.id}`} key={p.id}><span className="position-chip">{p.position}</span><div><h3>{p.name}</h3><p>{p.team} · {p.injury_status}</p></div><strong>{p.mean}<small> mean</small></strong><ArrowRight/></Link>)}</div></main>}
export function PlayerPage({id}:{id:string}){const [data,setData]=useState<any>();useEffect(()=>{api(`/api/players/${id}`).then(setData)},[id]);if(!data)return <main className="page"><Loading/></main>;return <main className="page"><Head eyebrow={`${data.player.team} · ${data.player.position}`} title={data.player.name} copy={`${data.role}. Weekly projection with explicit missing inputs.`}/><section className="metrics"><Metric label="FLOOR" value={data.projection.floor}/><Metric label="MEDIAN" value={data.projection.median}/><Metric label="CEILING" value={data.projection.ceiling}/><Metric label="CONFIDENCE" value={pct(data.projection.confidence)}/></section><div className="research-grid"><article><h2>Six-week form</h2><div className="trend-bars">{data.weekly_trend.map((x:number,i:number)=><div key={i}><i style={{height:`${Math.max(8,x*4)}px`}}/><span>W{i+1}</span><b>{x}</b></div>)}</div></article><article><h2>Why this range</h2>{data.explanation.map((x:string)=><p key={x}><CheckCircle2/> {x}</p>)}<p><ShieldCheck/> Player props: {data.market.state}</p></article></div></main>}

export function WhatIfPage(){const [data,setData]=useState<any>();const [remove,setRemove]=useState("");const [add,setAdd]=useState("");const [result,setResult]=useState<any>();useEffect(()=>{api("/api/what-if/options").then((x:any)=>{setData(x);setRemove(x.roster[0]?.id);setAdd(x.alternatives[0]?.id)})},[]);if(!data)return <main className="page"><Loading/></main>;async function run(){setResult(await api("/api/what-if",{method:"POST",body:JSON.stringify({remove_id:remove,add_id:add})}))}return <main className="page"><Head eyebrow="ROSTER SANDBOX" title="Change one assumption." copy="Swap any player, then rerun the same legal-lineup and matchup simulation."/><div className="whatif"><label>REMOVE<select value={remove} onChange={e=>setRemove(e.target.value)}>{data.roster.map((p:Player)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>ADD<select value={add} onChange={e=>setAdd(e.target.value)}>{data.alternatives.map((p:Player)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button className="button" onClick={run}><FlaskConical/> Run scenario</button></div>{result&&<div className="scenario-result"><Metric label="SCORE CHANGE" value={`${result.score_delta>=0?"+":""}${result.score_delta}`}/><Metric label="WIN CHANCE" value={`${result.win_probability_delta>=0?"+":""}${pct(result.win_probability_delta)}`}/><p>{result.remove.name} out, {result.add.name} in. The optimizer rebuilt every legal slot before comparing outcomes.</p></div>}</main>}

export function RankingsPage({standings=false}:{standings?:boolean}){const [data,setData]=useState<any>();useEffect(()=>{api(standings?"/api/standings-projection":"/api/power-rankings").then(setData)},[standings]);if(!data)return <main className="page"><Loading/></main>;return <main className="page"><Head eyebrow={standings?`THROUGH WEEK ${data.through_week}`:`${data.simulations.toLocaleString()} SIMULATIONS`} title={standings?"Projected final standings":"League power rankings"} copy={standings?"Expected final wins with an 80% simulation interval.":"Simulated strength separates roster quality from the current record."}/><div className="ranking-table"><div><span>#</span><span>TEAM</span><span>PROJ PTS</span><span>PLAYOFF</span><span>TITLE</span><span>FINAL WINS</span></div>{data.teams.map((t:Strength)=><div key={t.team_id}><b>{t.rank}</b><strong>{t.team_name}</strong><span>{t.expected_score}</span><span>{pct(t.playoff_probability)}</span><span>{pct(t.championship_probability)}</span><span>{t.projected_wins} <small>{t.wins_low}–{t.wins_high}</small></span></div>)}</div></main>}

export function TrustPage(){const [d,setD]=useState<any>();useEffect(()=>{api("/api/trust").then(setD)},[]);if(!d)return <main className="page"><Loading/></main>;return <main className="page"><Head eyebrow="MODEL CALIBRATION" title="Make the probabilities earn trust." copy="Read-only diagnostics compare stored predictions with observed results. They never silently tune the live model."/><section className="metrics"><Metric label="SAMPLE" value={d.sample_size}/><Metric label="POINTS MAE" value={d.points_mae}/><Metric label="BRIER SCORE" value={d.brier_score}/><Metric label="BIAS" value={d.confidence_bias}/></section><article className="calibration"><h2>{d.verdict}</h2><p>Lower Brier and MAE scores are better. This demo sample is intentionally small and is not evidence of production accuracy.</p><div>{d.buckets.map((b:any,i:number)=><span key={i}><i style={{height:`${b.observed*150}px`}}/><b>{pct(b.observed)}</b><small>{pct(b.predicted)} predicted · n={b.count}</small></span>)}</div></article></main>}

export function ReportsPage(){return <main className="page"><Head eyebrow="EXPORT CENTER" title="Take the decision brief with you." copy="Reports contain readable recommendations and simulation summaries—not raw backend dictionaries."/><div className="report-grid"><article><Download/><div><h2>Weekly league report</h2><p>Team projections, ranges, and simulated win context.</p></div><a className="button" href={`${API}/api/reports/weekly.csv`}>Download CSV</a></article></div></main>}
export function AskEngine(){const[q,setQ]=useState("");const[a,setA]=useState("");const[busy,setBusy]=useState(false);async function ask(e:FormEvent){e.preventDefault();setBusy(true);const result=await api<{answer:string}>("/api/ask",{method:"POST",body:JSON.stringify({question:q})});setA(result.answer);setBusy(false)}return <section className="ask-engine"><div><span className="tag">NO PAID LLM</span><h2>Ask the engine</h2><p>Ask about your lineup, waiver options, or generated trades.</p></div><form onSubmit={ask}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Who is my best waiver add?" required/><button className="button">{busy?"Checking...":"Ask"}</button></form>{a&&<p className="ask-answer">{a}</p>}</section>}
export function SettingsPage(){const [d,setD]=useState<any>();useEffect(()=>{api("/api/settings").then(setD)},[]);if(!d)return <main className="page"><Loading/></main>;return <main className="page"><Head eyebrow="LEAGUE CONFIGURATION" title={d.league.name} copy="Connection and privacy status. Secret values are never returned by this endpoint."/><section className="settings-grid"><article><h2>League</h2><p>Season <b>{d.league.season}</b></p><p>Week <b>{d.league.week}</b></p><p>Teams <b>{d.league.teams.length}</b></p></article><article><h2>Server credentials</h2>{Object.entries(d.privacy).map(([k,v])=><p key={k}><span className={`status ${v?"live":"unavailable"}`}>{v?"CONFIGURED":"MISSING"}</span> {k.replaceAll("_"," ")}</p>)}</article></section></main>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="mini-metric"><span>{label}</span><b>{value}</b></div>}
