"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, Check, ChevronRight, Clock3, RefreshCw, ShieldAlert, Sparkles, TrendingUp } from "lucide-react";
import { api } from "../lib/api";

type Player={id:string,name:string,position:string,team:string,injury_status:string};
type Entry={slot:string,player:Player,projection:{mean:number,floor:number,ceiling:number,confidence:number,reasons:string[],missing:string[]}};
type Lineup={style:string,starters:Entry[],bench:Player[],expected_score:number,floor:number,ceiling:number,win_probability:number,changes:string[]};
type Move={add:Player,drop:Player,weekly_gain:number,ros_gain:number,category:string,confidence:number,faab_percent:number,reasons:string[],risks:string[]};
type Overview={league:{name:string,week:number},team:{name:string,record:string},lineup:Lineup,actions:Move[],data_status:{provider:string,category:string,state:string,impact:string}[],mode:string};
function Load({error}:{error?:string}){return <div className="loading"><RefreshCw className="spin"/><b>{error||"Running the engine…"}</b></div>}
const pct=(n:number)=>`${Math.round(n*100)}%`;
export function OverviewPage(){const [data,setData]=useState<Overview>();const [err,setErr]=useState("");useEffect(()=>{api<Overview>("/api/overview").then(setData).catch(e=>setErr(e.message))},[]);if(!data)return <main className="page"><Load error={err}/></main>;return <main className="page"><PageHead eyebrow={`WEEK ${data.league.week} DECISION BRIEF`} title={`Good morning, ${data.team.name}.`} copy="Here’s what the model says matters before kickoff."/><section className="metrics"><Metric label="RECORD" value={data.team.record} note="3rd of 10"/><Metric label="PROJECTED" value={`${data.lineup.expected_score}`} note={`${data.lineup.floor}–${data.lineup.ceiling} range`}/><Metric label="WIN CHANCE" value={pct(data.lineup.win_probability)} note="Balanced lineup" accent/><Metric label="DATA HEALTH" value="3 / 5" note="sources available"/></section><section className="grid-main"><div><h2 className="section-title"><Sparkles/> Do this next</h2>{data.actions.map((m,i)=><article className="rec-card" key={m.add.id}><div className="rank">0{i+1}</div><div className="rec-copy"><span className="tag">{m.category}</span><h3>Add {m.add.name}</h3><p>Drop {m.drop.name}. {m.reasons[0]}.</p><div className="rec-meta"><span><TrendingUp/> +{m.weekly_gain} weekly points</span><span>{pct(m.confidence)} confidence</span></div></div><ChevronRight/></article>)}</div><aside className="matchup"><div className="card-top"><span>WEEK {data.league.week} MATCHUP</span><Clock3 size={16}/></div><div className="versus"><div><i>YOU</i><b>{data.lineup.expected_score}</b><span>Sunday Algorithms</span></div><em>VS</em><div><i>OPP</i><b>112.0</b><span>Gridiron Theory</span></div></div><div className="prob"><div style={{width:pct(data.lineup.win_probability)}}/><span>{pct(data.lineup.win_probability)} win probability</span></div><a href="/lineup" className="text-link">View lineup paths <ArrowRight/></a></aside></section><section><h2 className="section-title"><ShieldAlert/> Source status</h2><div className="source-row">{data.data_status.slice(0,4).map(s=><div key={s.provider}><span className={`status ${s.state.toLowerCase()}`}>{s.state}</span><b>{s.provider}</b><small>{s.category}</small></div>)}</div></section></main>}
export function LineupPage(){const [all,setAll]=useState<Record<string,Lineup>>();useEffect(()=>{api<Record<string,Lineup>>("/api/lineup").then(setAll)},[]);if(!all)return <main className="page"><Load/></main>;return <main className="page"><PageHead eyebrow="LINEUP OPTIMIZER" title="Choose your risk posture." copy="Same roster, three legal paths—evaluated against your opponent."/><div className="tabs">{Object.values(all).map(l=><article className={l.style==="balanced"?"lineup-card featured":"lineup-card"} key={l.style}><span className="tag">{l.style.toUpperCase()}</span><div className="lineup-score"><b>{l.expected_score}</b><span>projected points</span></div><div className="prob"><div style={{width:pct(l.win_probability)}}/></div><strong>{pct(l.win_probability)} chance to win</strong><div className="range"><span>Floor <b>{l.floor}</b></span><span>Ceiling <b>{l.ceiling}</b></span></div>{l.starters.map(e=><div className="player-row" key={e.player.id}><span>{e.slot}</span><div><b>{e.player.name}</b><small>{e.player.team} · {e.player.position}</small></div><strong>{e.projection.mean}</strong></div>)}</article>)}</div></main>}
export function WaiversPage(){const [moves,setMoves]=useState<Move[]>();useEffect(()=>{api<{moves:Move[]}>("/api/waivers").then(x=>setMoves(x.moves))},[]);if(!moves)return <main className="page"><Load/></main>;return <main className="page"><PageHead eyebrow="WAIVER DECISIONS" title="Upgrade the roster, not the headline." copy="Every candidate includes the actual cost: who leaves your team."/><div className="waiver-list">{moves.map(m=><article key={m.add.id}><div className="waiver-person"><span className="tag">{m.category}</span><h3>{m.add.name}</h3><p>{m.add.team} · {m.add.position}</p></div><div className="swap"><div><small>ADD</small><b>{m.add.name}</b></div><ArrowRight/><div><small>DROP</small><b>{m.drop.name}</b></div></div><div className="waiver-impact"><b>+{m.weekly_gain}</b><span>weekly points</span></div><div className="waiver-impact"><b>{m.faab_percent}%</b><span>suggested FAAB</span></div><div className="explain"><Check/> {m.reasons[0]}<br/><AlertTriangle/> {m.risks[0]}</div></article>)}</div></main>}
export function DataSourcesPage(){const [items,setItems]=useState<Overview["data_status"]>();useEffect(()=>{api<Overview["data_status"]>("/api/data-sources").then(setItems)},[]);return <main className="page"><PageHead eyebrow="TRANSPARENCY" title="Know what the engine knows." copy="Unavailable and demo sources are never styled as live."/><div className="data-table"><div className="table-head"><span>Provider</span><span>Category</span><span>Status</span><span>Impact</span></div>{items?.map(s=><div key={s.provider}><b>{s.provider}</b><span>{s.category}</span><span className={`status ${s.state.toLowerCase()}`}>{s.state}</span><span>{s.impact}</span></div>)}</div></main>}
function PageHead({eyebrow,title,copy}:{eyebrow:string,title:string,copy:string}){return <header className="page-head"><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></header>}
function Metric({label,value,note,accent}:{label:string,value:string,note:string,accent?:boolean}){return <article className={accent?"metric accent":"metric"}><span>{label}</span><b>{value}</b><small>{note}</small></article>}
