"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Activity, BarChart3, Database, Download, FlaskConical, Gauge, LineChart, LockKeyhole, Menu, Search, Settings, ShieldCheck, Sparkles, Trophy, Users, X, Zap } from "lucide-react";
import { useEffect, useState } from "react";
const links=[["/dashboard","Overview",Gauge],["/lineup","Lineup",Zap],["/waivers","Waivers",Sparkles],["/trades","Trades",Users],["/draft","Draft",Trophy],["/players","Players",Search],["/what-if","What-if",FlaskConical],["/power-rankings","Power rankings",BarChart3],["/standings-projection","Standings",LineChart],["/reports","Reports",Download],["/trust","Trust center",ShieldCheck],["/data-sources","Data sources",Database],["/privacy","Privacy",LockKeyhole],["/settings","Settings",Settings]] as const;
type FriendlyError={code:string;message:string;hint:string;retryable:boolean};
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname();const[open,setOpen]=useState(false);const[error,setError]=useState<FriendlyError>();const[warnings,setWarnings]=useState<string[]>([]);
 useEffect(()=>{const handler=(event:Event)=>setError((event as CustomEvent<FriendlyError>).detail);window.addEventListener("fourth-down-error",handler);const stored=sessionStorage.getItem("connection_warnings");if(stored){try{setWarnings(JSON.parse(stored))}catch{}sessionStorage.removeItem("connection_warnings")}return()=>window.removeEventListener("fourth-down-error",handler)},[]);
 return <div className="app-shell"><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><aside className={open?"sidebar open":"sidebar"}><Link className="brand" href="/"><span>4</span>TH DOWN</Link><div className="league-pill"><small>ACTIVE LEAGUE</small><b>Connected league</b><span>Decision workspace</span></div><nav>{links.map(([href,label,Icon])=><Link key={href} className={path===href?"active":""} href={href} onClick={()=>setOpen(false)}><Icon size={18}/>{label}</Link>)}</nav><div className="sidebar-foot"><Activity size={15}/><span>Engine ready</span></div></aside><div className="workspace"><header className="topbar"><div><small>FOURTH DOWN</small><b>Fantasy Decision Engine</b></div></header>{error&&<div className="global-error" role="alert"><div><b>{error.message}</b><p>{error.hint}</p><small>Error code: {error.code}</small></div>{error.retryable&&<button onClick={()=>location.reload()}>Try again</button>}<button aria-label="Dismiss error" onClick={()=>setError(undefined)}>×</button></div>}{warnings.length>0&&<div className="global-warning" role="status"><b>League connected with a warning</b>{warnings.map(item=><p key={item}>{item}</p>)}<button onClick={()=>setWarnings([])}>Dismiss</button></div>}{children}</div></div>
}
