[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 1
maxMessageSize = 10

[theme]
base = "dark"
primaryColor = "#F97316"
backgroundColor = "#080A0F"
secondaryBackgroundColor = "#11151D"
textColor = "#F8FAFC"
font = "sans serif"
